services:
  - type: web
    name: rune-backend
    env: docker
    plan: free
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: ALLOWED_ORIGIN
        value: https://rune-frontend.onrender.com

  - type: web
    name: rune-frontend
    env: docker
    plan: free
    dockerContext: ./client
    dockerfilePath: ./client/Dockerfile
    dockerArgs:
      build:
        args:
          VITE_API_BASE_URL: https://rune-backend.onrender.com
