export { LandingHero } from './LandingHero'
export { LandingHowItWorks } from './LandingHowItWorks'
export { LandingMethodologies } from './LandingMethodologies'
export { LandingCapabilities } from './LandingCapabilities'
export { LandingFAQ } from './LandingFAQ'
export { LandingFooter } from './LandingFooter'
export { SectionHeading } from './SectionHeading'
